### ISSUE TITLE
Поменять аву и добавить команды

### ISSUE THREAD

**Issue by alef4yuj** [wellWINeo/mptBot#4]
А можно аву в боте поменять? Добавить кнопки расписания и замен например как тут:
![image](https://user-images.githubusercontent.com/80422299/110686181-3407e980-81f0-11eb-8825-fac633f10334.png) спс бро

**Comment by wellWINeo** [comment]
Кнопки меню как раз планирую. А насчет авы чем не нравиться? (я просто не знаю чем ее можно было бы заменить)
Спасибо за предложения ^_^

**Comment by wellWINeo** [comment]
Добавил клавиатуру с некоторыми командами, со временем дополню ее
