### ISSUE TITLE
Text message issues

### ISSUE THREAD

**Issue by userNameIsBoris** [wellWINeo/mptBot#5]
Hey. There are some issues with text messages: missing spaces and commas. Example of missing spaces is shown in the screenshot below.
![image](https://user-images.githubusercontent.com/68778381/111022624-e30d1680-83e4-11eb-80e1-422e36c38207.png)

**Comment by userNameIsBoris** [comment]
Another good idea is to replace the minus sign (-) with an em dash (—). The latter looks way better

**Comment by userNameIsBoris** [comment]
Also replace every incorrect word "**shedule**" with correct "**schedule**". I saw it in the README, about text and maybe somewhere else

**Comment by wellWINeo** [comment]
> Also replace every incorrect word "**shedule**" with correct "**schedule**". I saw it in the README, about text and maybe somewhere else

Yeah, i also noticed this typo, but it exists in many files, so i'm working on fixing this typo
